class InvaderGrid {
    /**
     * @description sets instance variables and initializes objects, including myColors,
     * canvasSize, numCells, cellSize, mode, and modifier.
     *
     * @param { array } myColors - 1D array of colors that define the appearance of each
     * cell in the game, with each element in the array specifying the color of a particular
     * cell.
     *
     * @param { integer } canvasSize - size of the canvas that the code will operate on,
     * which is used to calculate the size of each cell in the grid.
     */
    constructor(myColors, canvasSize) {
        this.myColors = myColors;
        this.canvasSize = canvasSize;
        this.cellSize = this.canvasSize / 200;
        this.mode = 0;
        this.modifier = 0.0;
        this.sqrtNumInv = 10;
        this.numInvaders = this.sqrtNumInv * this.sqrtNumInv;
        this.geoIncrement = this.canvasSize / (this.sqrtNumInv + 1);
        this.invaders = [];
        for (let i = 0; i < this.numInvaders; i++) {
            this.invaders.push(this.invader());
        }
    }

    /**
     * @description is a utility function that adapts to the current state, performing
     * appropriate actions based on the mode parameter.
     */
    draw() {
        noStroke();
        switch (this.mode) {
            case 0:
                break;
            case 1:
                this.static();
                break;
            case 2:
                this.in();
                break;
            case 3:
                this.out();
                break;
            default:
                break;
        }
    }

    /**
     * @description updates a modifier variable and changes its value depending on a
     * condition, then calls `static()` method.
     */
    in() {
        this.modifier += 0.1;
        if (this.modifier >= 1.0) {
            this.modifier = 1.0;
            this.mode = 1;
            // setTimeout(() => {frameRate(1);}, 1000);
        }
        this.static();
    }

    /**
     * @description modifies the value of an object's `modifier` property by subtracting
     * a fraction (0.1) and sets its `mode` property to 0 if the modified value is below
     * 0.
     */
    out() {
        this.modifier -= 0.1;
        if (this.modifier <= 0.0) {
            this.mode = 0;
            this.modifier = 0.0;
        }
        this.static();
    }

    /**
     * @description generates a grid of squares based on user-defined parameters, with
     * invaders that move and change color when hit by laser beams.
     */
    static() {
        rectMode(CENTER);
        let theColors = ["teal", "brickRed", "goldenYellow"];
        let x = 0;
        let y = 0;
        let counter = 0;
        // Drawing part
        for (let i = 0; i < this.sqrtNumInv; i++) {
            x += this.geoIncrement;
            y = 0;
            for (let j = 0; j < this.sqrtNumInv; j++) {
                y += this.geoIncrement;
                let invader = this.invaders[counter];
                let grid = invader.grid;
                let threshold = invader.threshold;
                let invLength = invader.length;
                let invHeight = invader.height;
                fill(this.myColors[theColors[counter%theColors.length]]);

                for (let isMirrored of [false, true]) {
                    for (let i = 0; i < invLength; i++) {
                        for (let j = 0; j < invHeight; j++) {
                            if (grid[isMirrored ? invLength - i - 1 : i][j] > threshold) {
                                const xPos = x + (isMirrored ? i : i - invLength) * this.cellSize;
                                const yPos = y + j * this.cellSize - Math.floor(invHeight / 2) * this.cellSize;
                                push();
                                translate(xPos, yPos);
                                rotate(this.modifier * PI);
                                square(0, 0, this.modifier * (this.cellSize + 1));
                                pop();
                            }
                        }
                    }
                }
                counter += 1;
            }
        }
    }

    /**
     * @description generates a random number within a specified range. It takes two
     * arguments, `min` and `max`, and returns an integer value calculated using the
     * formula `(Math.random() * (max - min) + min)`.
     * 
     * @param { number } min - minimum value that the random number generated by the
     * function can take.
     * 
     * @param { number } max - maximum value that the random number can take, which is
     * used to calculate the range of possible values returned by the `randomInRange()`
     * function.
     * 
     * @returns { integer } a number between `min` and `max`, inclusive of `min`.
     */
    randomInRange(min, max) {
        return Math.floor(Math.random() * (max - min) + min);
    }

    /**
     * @description generates a 2D grid of random values within a specified range,
     * normalizes and calculates a threshold value, and returns an object containing the
     * grid, threshold, length, and height.
     * 
     * @returns { object } an object containing the normalized grid of random values, a
     * threshold value, and the length and height of the grid.
     */
    invader() {
        //crab 8 x 11
        //squid 8 x 8
        //octopus 8 x 12
        let invLength = this.randomInRange(5, 7);
        let invHeight = this.randomInRange(8, 8);
        fill(255);
        stroke(255);

        let maxVal = 0.0;
        let sum = 0;
        let count = 0;
        /**
         * @description generates an array of random values within a given range, with two
         * sine waves combined to create a curved output.
         * 
         * @param { 3D coordinates vector. } _ - 2D coordinate at which the random height is
         * generated.
         * 
         * 		- `length`: A number indicating the length of the array.
         * 		- `i`: A number indicating the position of the current element in the array,
         * ranging from 0 to `length - 1`.
         * 		- `j`: A number indicating the position of the current element in the second
         * array, ranging from 0 to `invHeight - 1`.
         * 
         * 	The various attributes of `_` are:
         * 
         * 		- `val`: The random value generated for each element, ranging from -2 to 2.
         * 		- `maxVal`: The maximum value among all elements, which is set to the maximum
         * of the values in `_` and updated at each iteration.
         * 
         * 
         * @param { integer } i - 2D coordinate (row and column) of a point within an array,
         * which is used to generate random values for each position in the array.
         * 
         * @returns { array } an array of random values within a range of -1 to 1, with each
         * value influenced by both position and height.
         */
        /**
         * @description takes two parameters `i` and `j`, computes and returns a random value
         * between -1 and 1, with additional sine-modulated values based on `i` and `j`.
         * 
         * @param { 2D vector of unspecified origin or origin type. } _ - 19th argument passed
         * to the function and is used in the calculation of `val`.
         * 
         * 		- `j`: an integer parameter that takes on distinct values from 0 to 179 (excluded)
         * and is used in calculating the resulting value `val`.
         * 		- `i`: an integer parameter that takes on distinct values from 0 to 179 (excluded)
         * and is used in calculating the resulting value `val`.
         * 		- `Math.random()`: a function that generates a random number between 0 and 1,
         * which is multiplied by a scalar `2` to generate a random number between 0 and 2.
         * 		- `Math.sin()`: a function that calculates the sine of a given angle in radians,
         * with the arguments `(Math.PI * 90 * i) / invLength` and `(Math.PI * 180 * j) /
         * invHeight`. The values of `i` and `j` are used to calculate two different sine
         * values, which are then added together to generate the final value `val`.
         * 		- `maxVal`: a variable that stores the maximum possible value for `val`, which
         * is calculated by comparing the current value of `val` to its previous value.
         * 
         * 
         * @param { integer } j - 2D pixel position in the image and affects the computation
         * of the random value through the addition of a sine wave component relative to its
         * position.
         * 
         * @returns { number } a random value between -1 and 1, inclusive, with additional
         * sinusoidal components based on `i` and `j`.
         */
        const grid = Array.from({ length: invLength }, (_, i) =>
            Array.from({ length: invHeight }, (_, j) => {
                let val = Math.random() * 2;
                val += Math.sin((Math.PI * 90 * i) / invLength / 180);
                val += Math.sin((Math.PI * 180 * j) / invHeight / 180);

                maxVal = Math.max(maxVal, val);
                return val;
            })
        );

        // Normalizing and calculating the threshold
        grid.forEach((row) =>
            row.forEach((cell, j) => {
                const normalizedCell = cell / maxVal;
                row[j] = normalizedCell;
                sum += normalizedCell;
                count++;
            })
        );
        const threshold = sum / count;
        return { grid: grid, threshold: threshold, length: invLength, height: invHeight };
    }
}
