#!/usr/bin/env python3
"""
Generates the static background texture in _includes/art.html.

Value-noise field (fractal, a few octaves) mapped onto a density ramp drawn from
the Unicode Geometric Shapes block, with a handful of mirrored invader sprites
stamped into it. Run once and commit the result -- it is decoration, so there is
no reason to pay for it at runtime.

    python3 tools/gen_art.py
"""
import math
import random

SEED = 20260926
COLS, ROWS = 46, 120

# Light to heavy. Anything here must be single-width in a monospace font or the
# grid shears; check the rendered page after changing it.
RAMP = [" ", "▫", "◦", "▪", "◇", "◆"]
INVADER_GLYPH = "▪"
# True: invaders get a cleared margin so the silhouettes read.
# False: they dissolve into the noise field, which is also fine.
CLEAR_AROUND_INVADERS = True


def smooth(t):
    return t * t * (3 - 2 * t)


def lerp(a, b, t):
    return a + (b - a) * t


class ValueNoise:
    def __init__(self, seed):
        self._rng = random.Random(seed)
        self._cache = {}

    def _corner(self, ix, iy):
        key = (ix, iy)
        if key not in self._cache:
            self._cache[key] = random.Random(hash(key) ^ SEED).random()
        return self._cache[key]

    def at(self, x, y):
        x0, y0 = math.floor(x), math.floor(y)
        tx, ty = smooth(x - x0), smooth(y - y0)
        top = lerp(self._corner(x0, y0), self._corner(x0 + 1, y0), tx)
        bot = lerp(self._corner(x0, y0 + 1), self._corner(x0 + 1, y0 + 1), tx)
        return lerp(top, bot, ty)


def fbm(noise, x, y, octaves=4):
    total = amplitude = norm = 0.0
    frequency = 1.0
    amplitude = 1.0
    for _ in range(octaves):
        total += noise.at(x * frequency, y * frequency) * amplitude
        norm += amplitude
        amplitude *= 0.5
        frequency *= 2.0
    return total / norm


def invader(rng, width=7, height=6):
    """Half a sprite, mirrored -- the same trick the old p5 index used."""
    half = (width + 1) // 2
    rows = []
    for _ in range(height):
        left = [rng.random() < 0.55 for _ in range(half)]
        rows.append(left + left[-2::-1])
    return rows


def main():
    rng = random.Random(SEED)
    noise = ValueNoise(SEED)

    grid = [[" "] * COLS for _ in range(ROWS)]
    for y in range(ROWS):
        for x in range(COLS):
            v = fbm(noise, x / 9.0, y / 7.0)
            # Bias density toward the right edge so it thins out before the fade.
            v *= 0.35 + 0.65 * (x / (COLS - 1))
            idx = int(v * len(RAMP) * 1.35)
            grid[y][x] = RAMP[min(idx, len(RAMP) - 1)]

    for _ in range(7):
        sprite = invader(rng)
        sh, sw = len(sprite), len(sprite[0])
        sy = rng.randrange(2, ROWS - sh - 2)
        sx = rng.randrange(COLS // 2, COLS - sw - 1)
        for dy in range(-1, sh + 1) if CLEAR_AROUND_INVADERS else ():
            for dx in range(-1, sw + 1):
                y, x = sy + dy, sx + dx
                if 0 <= y < ROWS and 0 <= x < COLS:
                    grid[y][x] = " "
        for dy, row in enumerate(sprite):
            for dx, on in enumerate(row):
                if on:
                    grid[sy + dy][sx + dx] = INVADER_GLYPH

    # No rstrip: every row keeps the full grid width so the block stays square.
    body = "\n".join("".join(row) for row in grid)
    with open("_includes/art.html", "w") as fh:
        fh.write(
            "<!-- Generated by tools/gen_art.py -- edit that, not this. -->\n"
            '<div class="art" role="presentation" aria-hidden="true">\n'
            f"<pre>{body}</pre>\n"
            "</div>\n"
        )
    print(f"_includes/art.html: {COLS}x{ROWS}, {len(body)} chars")


if __name__ == "__main__":
    main()
