#!/usr/bin/env python3
"""
Generates WebP derivatives for the images shown on the card pages, and writes
_data/images.yml so templates can emit accurate width/height and srcset.

Non-destructive: originals are never touched. Derivatives sit beside them as
<name>-760.webp and <name>-1600.webp. Idempotent -- a derivative newer than its
source is left alone, so re-running is cheap.

    python3 tools/optimize_images.py            # build derivatives + manifest
    python3 tools/optimize_images.py --check    # report only, exit 1 if stale

Cards render at about 380 CSS px, so 760 covers a 2x display. 1600 is there for
the larger preview on a demo post page.
"""
import argparse
import os
import sys

from PIL import Image

# Driven by the posts themselves rather than a directory list: card art is
# spread across images/previews, images/covers and the older img/ folder.
POST_GLOB = "_posts/*.markdown"
FRONT_MATTER_KEYS = ("image", "albumcover")
WIDTHS = [760, 1600]
QUALITY = 82
MANIFEST = "_data/images.yml"
EXTS = (".png", ".jpg", ".jpeg")


def sources():
    """Every image a demo or release card points at, resolved to a local path."""
    import glob
    import re

    found = set()
    for post in glob.glob(POST_GLOB):
        text = open(post, encoding="utf8", errors="replace").read()
        for key in FRONT_MATTER_KEYS:
            m = re.search(rf'^{key}:\s*["\']?([^"\'\n]+)', text, re.M)
            if not m:
                continue
            path = m.group(1).strip()
            path = path.replace("https://b38tn1k.github.io/", "").lstrip("/")
            if path.lower().endswith(EXTS) and os.path.isfile(path):
                found.add(path)
    return sorted(found)


def derivative_path(src, width):
    stem, _ = os.path.splitext(src)
    return f"{stem}-{width}.webp"


def stale(src, out):
    return not os.path.exists(out) or os.path.getmtime(out) < os.path.getmtime(src)


def build(check_only=False):
    entries = {}
    made = skipped = 0
    saved_from = saved_to = 0

    for src in sources():
        with Image.open(src) as im:
            w, h = im.size
            rgb = im.convert("RGB")
            widths = []
            for target in WIDTHS:
                # Never upscale: a 700px source has no business becoming 1600px.
                if target > max(w, h) and target != min(WIDTHS):
                    continue
                out = derivative_path(src, target)
                widths.append((target, out))
                if not stale(src, out):
                    skipped += 1
                    continue
                if check_only:
                    made += 1
                    continue
                copy = rgb.copy()
                copy.thumbnail((target, target), Image.LANCZOS)
                copy.save(out, "WEBP", quality=QUALITY, method=6)
                made += 1

        entry = {"w": w, "h": h}
        for target, out in widths:
            if os.path.exists(out):
                entry[f"w{target}"] = "/" + out
                saved_to += os.path.getsize(out)
        entries[src] = entry
        saved_from += os.path.getsize(src)

    if check_only:
        print(f"{made} derivative(s) missing or stale, {skipped} current")
        return 1 if made else 0

    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    with open(MANIFEST, "w") as fh:
        fh.write("# Generated by tools/optimize_images.py -- do not edit by hand.\n")
        for src, e in sorted(entries.items()):
            fh.write(f'"{src}":\n')
            for k, v in e.items():
                fh.write(f"  {k}: {v!r}\n" if isinstance(v, str) else f"  {k}: {v}\n")

    print(f"{len(entries)} sources, {made} derivative(s) written, {skipped} already current")
    print(f"originals {saved_from/1024/1024:.1f} MB -> derivatives {saved_to/1024/1024:.1f} MB")
    print(f"manifest: {MANIFEST}")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report staleness, do not write")
    sys.exit(build(check_only=ap.parse_args().check))
